# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maiwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
    
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 408)
        MainWindow.setStyleSheet("""
        /*MainWindow*/
            #MainWindow {
                background-color: #282a36
            }
        /*QPushButton*/
            QPushButton {
                background-color:#6272a4;
                color: #000000
            }

            QLabel {
                color: white
            }

        /*QTableWidget*/
            QTableWidget {
                background-color: #282a36; 
                border-radius: 0px;
                font-size: 20px;
                selection-background-color: #282a36
            }
            QTableWidget::item {
                color: #f8f8f2;                    
                background-color: #44475a;
                margin-top: 5px;          
                border-radius: 0px;
                padding-left: 2px;
            }
            QHeaderView::section {
                background-color:#6272a4;
                selection-color: #000000;
            }
            QTableWidget::item:hover {
                background-color: #6272a4;
                color : black;
            }
            QTableWidget .QPushButton {
                background-color: #282a36;
                color: white
            }
        """)
        
        self.tblWidgetTopics = QtWidgets.QTableWidget(MainWindow)
        self.tblWidgetTopics.setGeometry(QtCore.QRect(60, 130, 640, 240))
        self.tblWidgetTopics.setObjectName("tblWidgetTopics")
        self.tblWidgetTopics.setColumnCount(3)
        self.tblWidgetTopics.setRowCount(1)
        self.tblWidgetTopics.setShowGrid(False)
        self.tblWidgetTopics.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tblWidgetTopics.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblWidgetTopics.horizontalHeader().setVisible(False)
        self.tblWidgetTopics.verticalHeader().setVisible(False)
        item = QtWidgets.QTableWidgetItem()
        self.tblWidgetTopics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWidgetTopics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWidgetTopics.setHorizontalHeaderItem(2, item)
        self.tblWidgetTopics.setColumnWidth(0,80)
        self.tblWidgetTopics.setColumnWidth(1,400)
        self.tblWidgetTopics.setColumnWidth(2,140)

        self.lblDecks = QtWidgets.QLabel(MainWindow)
        self.lblDecks.setGeometry(QtCore.QRect(320, 100, 67, 18))
        self.lblDecks.setObjectName("lblDecks")
        self.lblClass = QtWidgets.QLabel(MainWindow)
        self.lblClass.setGeometry(QtCore.QRect(50, 30, 67, 18))
        self.lblClass.setObjectName("lblClass")

        self.listView = QtWidgets.QListView(MainWindow)
        self.listView.setGeometry(QtCore.QRect(100, 30, 81, 16))
        self.listView.setObjectName("listView")

        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(430, 30, 88, 26))
        self.pushButton.setObjectName("pushButton")

        self.btnAddCards = QtWidgets.QPushButton(MainWindow)
        self.btnAddCards.setGeometry(QtCore.QRect(530, 30, 88, 26))
        self.btnAddCards.setObjectName("btnAddCards")

        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setGeometry(QtCore.QRect(30, 70, 641, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line.setStyleSheet("border-color: black")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", u"Flashcards"))
        
        item = self.tblWidgetTopics.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", u"hints_percentage"))
        item = self.tblWidgetTopics.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", u"deck_name"))
        item = self.tblWidgetTopics.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", u"btn_action"))
        
        self.lblDecks.setText(_translate("MainWindow", u"Decks"))
        self.lblClass.setText(_translate("MainWindow", u"Class:"))
        self.pushButton.setText(_translate("MainWindow", u"More Info"))
        self.btnAddCards.setText(_translate("MainWindow", u"Add Cards"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
